main.datasource.url=${MAIN_DATASOURCE_URL}
main.datasource.username=${MAIN_DATASOURCE_USERNAME}
main.datasource.password=${MAIN_DATASOURCE_PASSWORD}
main.datasource.driver-class-name=org.postgresql.Driver