apiVersion: v1
kind: ConfigMap
metadata:
  name: chronos-config
data:
  MAIN_DATABASE_NAME: "chronos_db"
  MAIN_DATASOURCE_URL: "jdbc:postgresql://postgresql/chronos_db"
  MAIN_DATASOURCE_USERNAME: "chronos_user"
  MAIN_DATASOURCE_PASSWORD: "chronos_pwd"